coruja_bdd:
    resource: "@CorujaBddBundle/Controller/"
    type:     annotation
    prefix:   /

courses:
    pattern: /
    defaults: { _controller: CorujaBddBundle:Courses:list }
    requirements:
        _method: GET
